# Generated by Django 3.2 on 2021-05-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('judul_buku', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField(max_length=3)),
                ('kategori', models.CharField(max_length=10)),
                ('sinopsis', models.TextField(max_length=1000)),
                ('gambar', models.ImageField(upload_to='book_images/')),
            ],
            options={
                'ordering': ('-judul_buku',),
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('no_lokasi', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama_seksi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id_peminjam', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('dept_name', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendataan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pendataan', models.DateField(auto_now_add=True)),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.petugas')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.buku')),
            ],
        ),
        migrations.CreateModel(
            name='Mengurusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_urusan', models.DateField(auto_now_add=True)),
                ('id_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam')),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.petugas')),
            ],
        ),
        migrations.CreateModel(
            name='Meminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField(auto_now_add=True)),
                ('tanggal_pengembalian', models.DateField()),
                ('status_peminjaman', models.CharField(max_length=10, null=True)),
                ('id_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.buku')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('dept_name', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=13)),
                ('nim', models.CharField(max_length=9)),
                ('id_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam')),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('dept_name', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=13)),
                ('nip', models.CharField(max_length=18)),
                ('id_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam')),
            ],
        ),
        migrations.CreateModel(
            name='Denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_denda', models.CharField(max_length=20)),
                ('id_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam')),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='no_lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.lokasi'),
        ),
    ]
