# Generated by Django 3.2 on 2021-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(default=None, upload_to='book_images/'),
        ),
    ]
