# Generated by Django 3.2 on 2021-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_alter_buku_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='judul_buku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
