# Generated by Django 3.2 on 2021-05-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_auto_20210505_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateField(null=True),
        ),
    ]
