# Generated by Django 3.2 on 2021-05-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_alter_meminjam_tanggal_pengembalian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='no_telepon',
        ),
    ]
