# Generated by Django 3.2 on 2021-05-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0006_auto_20210505_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='id_peminjam',
        ),
        migrations.AddField(
            model_name='peminjam',
            name='nim',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='peminjam',
            name='nip',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='peminjam',
            name='tipe',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
