# Generated by Django 3.2 on 2021-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0008_auto_20210505_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='jumlah_buku',
            field=models.IntegerField(),
        ),
    ]
