# Generated by Django 3.2 on 2021-05-05 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_api', '0010_auto_20210505_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_peminjaman',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 9, 24, 40, 543705, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 9, 24, 40, 543768, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='mengurusi',
            name='id_petugas',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mengurusi',
            name='tanggal_urusan',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 9, 24, 40, 544865, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pendataan',
            name='id_petugas',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendataan',
            name='tanggal_pendataan',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 5, 9, 24, 40, 544469, tzinfo=utc), editable=False),
        ),
    ]
