# Generated by Django 3.2 on 2021-05-05 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_api', '0011_auto_20210505_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_peminjaman',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mengurusi',
            name='id_petugas',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mengurusi',
            name='tanggal_urusan',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pendataan',
            name='id_petugas',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendataan',
            name='tanggal_pendataan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
