# Generated by Django 3.2 on 2021-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0012_auto_20210505_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='status_peminjaman',
            field=models.CharField(default='Belum Dikembalikan', max_length=10),
        ),
    ]
