# Generated by Django 3.2 on 2021-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0017_alter_meminjam_status_peminjaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='status_peminjaman',
            field=models.CharField(default='Belum Dikembalikan', max_length=300, null=True),
        ),
    ]
