# Generated by Django 3.2 on 2021-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0024_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(null=True),
        ),
    ]
