# Generated by Django 3.2 on 2021-05-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0026_auto_20210506_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='mengurusi',
            name='jenis',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
