# Generated by Django 3.2 on 2021-05-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0027_mengurusi_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_peminjaman',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pendataan',
            name='tanggal_pendataan',
            field=models.DateTimeField(),
        ),
    ]
