# Generated by Django 3.2 on 2021-05-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0028_auto_20210506_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mengurusi',
            name='tanggal_urusan',
            field=models.DateTimeField(),
        ),
    ]
