# Generated by Django 3.2 on 2021-05-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0029_alter_mengurusi_tanggal_urusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meminjam',
            name='id_peminjam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_api.peminjam'),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='isbn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_api.buku'),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_peminjaman',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meminjam',
            name='tanggal_pengembalian',
            field=models.DateTimeField(),
        ),
    ]
