# Generated by Django 3.2 on 2021-05-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0033_alter_meminjam_tanggal_pengembalian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(upload_to='book_images/'),
        ),
    ]
