# Generated by Django 3.2 on 2021-05-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0037_alter_meminjam_id_peminjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='denda',
            name='jumlah_hari_telat',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denda',
            name='status',
            field=models.CharField(default='Hutang', max_length=20),
        ),
    ]
