# Generated by Django 3.2 on 2021-05-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0039_alter_denda_jumlah_hari_telat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denda',
            name='status',
            field=models.CharField(blank=True, default='Hutang', max_length=20),
        ),
    ]
