# Generated by Django 3.2 on 2021-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0040_alter_denda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denda',
            name='jumlah_hari_telat',
            field=models.IntegerField(),
        ),
    ]
